<?php
/**
 * @file
 * Code for the commo_ck feature.
 */

include_once 'commo_ck.features.inc';

/**
 * Implements hook_menu_block_tree_alter().
 *
 * Only show active tree parents for the commo_ck menu items.
 * ref. https://drupal.org/node/406568#comment-6496988
 *
 * fixme: menu tree keys are hard coded.
 */
function commo_ck_menu_block_tree_alter(&$tree, &$config) {
  if ($config['label'] == 'commo ck module menu') {
    $get_help_key = _find_key_match('Get Help', $tree);
    $commo_ck_key = _find_key_match('Commotion Construction Kit', $tree[$get_help_key]['below']);
    if (!$commo_ck_key) { return; }
    $ck_tree = &$tree[$get_help_key]['below'][$commo_ck_key]['below'];
    foreach ($ck_tree as $key => $menu_data) {
      if ($menu_data['link']['in_active_trail'] === FALSE) {
        unset($ck_tree[$key]);
      }
      else {
        $level_2 = $ck_tree[$key]['below'];
        $hasActiveChildren = false;
        foreach ($level_2 as $menu_item_key => $menu_item) {
          $link = $menu_item['link'];
          if (isset($link['in_active_trail']) && $link['in_active_trail']) {
            $hasActiveChildren = true;
          }
        }
        foreach ($level_2 as $menu_item_key => $menu_item) {
          $link = $menu_item['link'];
          if (!isset($link['in_active_trail']) || ! $link['in_active_trail']) {
            // get rid of children since they are not in the active trail
            if ($hasActiveChildren) {
              unset($ck_tree[$key]['below'][$menu_item_key]);
            }
          }
        }
      }
    }
  }
}

/**
 * Find the key name that matches text string
 *
 * @param $search
 * @param $array
 *
 * @return
 *   string array key if one match
 *   FALSE if no or multiple matches
 */
function _find_key_match($search, $array) {
  $matches = array_filter(array_keys($array), function($el) use ($search) {
    return ( strpos($el, $search) !== false );
  });
  if (count($matches) === 1) {
    return array_pop($matches);
  }
  else {
    return FALSE;
  }
}

